language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
script: "RAILS_ENV=test bundle exec rake test"
env:
  - DB=sqlite
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "RAILS_ENV=test bundle exec rake db:migrate"
notifications:
  email:
    - kdbeswic@ncsu.edu
