---
- name: rvm fix-permissions system
  command: /bin/bash -lc 'rvm fix-permissions system'
- name: add users to rvm group
  command: /bin/bash -lc 'rvm group add rvm {{item}}'
  with_items: "{{users}}"
