---
- name: create /opt/rails/{{project_name}}
  file:
    path: /opt/rails/{{project_name}}
    state: directory
- name: symlink /opt/rails/project_name/current to /vagrant
  file:
    path: /opt/rails/{{project_name}}/current
    src: /vagrant
    state: link
    force: yes
  notify: restart httpd
